version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
    volumes:
      - ".:/go/src/github.com/OdaDaisuke/emo-lyrics-api"
    working_dir: /go/src/github.com/OdaDaisuke/emo-lyrics-api
    ports:
      - "80:8080"
    links:
      - db
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
    driver: local
