[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/mrjones/oauth"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "google.golang.org/appengine"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/godo.v2"
  version = "2.0.9"